all:
  hosts:
    localhost:
      ansible_connection: local
    vps:
      ansible_host: "{{ lookup('env', 'TF_VAR_vps_ip') }}"
      ansible_user: root
      ansible_ssh_private_key_file: /tmp/ssh_key
